const list = [
    {
      id: 1,
      title: "My First Book of Pencil Control",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 89,
      img: "id1.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "108 Panchatantra Stories",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 98,
      img: "id2.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Amazing Questions & Answers Science",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 143,
      img: "id3.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "My First Book of Pencil Control",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 57,
      img: "id4.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "My First 1000 Words",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 149,
      img: "id5.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "101 Panchatantra Stories for Children",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 135,
      img: "id6.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Pre-School Activities Pack ",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 693,
      img: "id7.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Early Learning Library Pack 1",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 289,
      img: "id8.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Blossom Moral Story Book for Kids ",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 80,
      img: "id9.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Brain Activity Book for Kids",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 86,
      img: "id10.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Willy the Silly Panda",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 120,
      img: "id11.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Grandma's Bag of Stories",
      author: "by Victoria Textile | 2023 | Ціна вказана за метр",
      price: 157,
      img: "id12.jpg",
      amount: 1,
    },
    {
        id: 13,
        title: "My First Book of Pencil Control",
        author: "by Victoria Textile | 2023 | Ціна вказана за метр",
        price: 89,
        img: "id13.jpg",
        amount: 1,
      },
      {
        id: 14,
        title: "108 Panchatantra Stories",
        author: "by Victoria Textile | 2023 | Ціна вказана за метр",
        price: 98,
        img: "id14.jpg",
        amount: 1,
      },
      {
        id: 15,
        title: "Amazing Questions & Answers Science",
        author: "by Victoria Textile | 2023 | Ціна вказана за метр",
        price: 143,
        img: "id15.jpg",
        amount: 1,
      },
      {
        id: 16,
        title: "My First Book of Pencil Control",
        author: "by Victoria Textile | 2023 | Ціна вказана за метр",
        price: 57,
        img: "id16.jpg",
        amount: 1,
      },
      {
        id: 17,
        title: "My First 1000 Words",
        author: "by Victoria Textile | 2023 | Ціна вказана за метр",
        price: 149,
        img: "id17.jpg",
        amount: 1,
      },
      {
        id: 18,
        title: "101 Panchatantra Stories for Children",
        author: "by Victoria Textile | 2023 | Ціна вказана за метр",
        price: 135,
        img: "id18.jpg",
        amount: 1,
      }
];

export default list; 